name: Check Vulnerabilities in the project

on: [push]

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  push:
    uses: nolram/github-actions/.github/workflows/check_vulnerability.yml@main
    with:
      project_type: "python"
    secrets: inherit
